
- name: Terminate instances
  hosts: localhost
  connection: local
  vars_files:
    - var.yml
  gather_facts: False

  tasks:
  - name: Terminate instances that were previously launched
    ec2:
     aws_access_key: "{{aws_access_key}}"
     aws_secret_key: "{{aws_secret_key}}"
     region:  "{{aws_region}}"
     state: 'absent'
     instance_ids: 
         - i-033e11868a76239b2
         - i-0c7def96ffd49fb8e


